name: Build Flatpak (ARM only)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  flatpak:
    name: "Flatpak ARM"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-5.15-24.08
      options: --privileged
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install xvfb and subversion
        run: sudo apt-get update && sudo apt-get install -y xvfb subversion
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: nz.mega.MEGAsync.aarch64.flatpak
          manifest-path: nz.mega.MEGAsync.yml
          cache-key: flatpak-builder-${{ github.sha }}-aarch64
          arch: aarch64

      - name: Upload Flatpak as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle-aarch64
          path: nz.mega.MEGAsync.aarch64.flatpak

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: nz.mega.MEGAsync.aarch64.flatpak